# Generated by Django 5.2.10 on 2026-01-10 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='브랜드명')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='로고')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '차량 브랜드',
                'verbose_name_plural': '차량 브랜드',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='연료타입')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '연료 타입',
                'verbose_name_plural': '연료 타입',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='차종명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='kiosk.carbrand', verbose_name='브랜드')),
            ],
            options={
                'verbose_name': '차종',
                'verbose_name_plural': '차종',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EngineOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='오일명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('fuel_types', models.ManyToManyField(related_name='oils', to='kiosk.fueltype', verbose_name='적용 연료타입')),
            ],
            options={
                'verbose_name': '엔진오일',
                'verbose_name_plural': '엔진오일',
                'ordering': ['order', 'name'],
            },
        ),
    ]
