# Generated by Django 5.2.6 on 2026-01-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='서비스명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '추가 서비스',
                'verbose_name_plural': '추가 서비스',
                'ordering': ['order', 'name'],
            },
        ),
    ]
