# Generated by Django 5.2.6 on 2026-01-10 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_additionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(blank=True, max_length=20, verbose_name='차량번호')),
                ('oil_tier', models.CharField(max_length=20, verbose_name='오일 등급')),
                ('oil_name', models.CharField(max_length=50, verbose_name='오일명')),
                ('oil_product_name', models.CharField(max_length=100, verbose_name='제품명')),
                ('oil_price', models.PositiveIntegerField(verbose_name='오일 가격')),
                ('mileage_current', models.PositiveIntegerField(blank=True, null=True, verbose_name='현재 주행거리')),
                ('mileage_next', models.PositiveIntegerField(blank=True, null=True, verbose_name='다음 교체 주행거리')),
                ('status', models.CharField(choices=[('pending', '대기'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.carbrand', verbose_name='브랜드')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.carmodel', verbose_name='차종')),
                ('fuel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.fueltype', verbose_name='연료타입')),
            ],
            options={
                'verbose_name': '시공 주문',
                'verbose_name_plural': '시공 주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='서비스명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='kiosk.serviceorder', verbose_name='주문')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.additionalservice', verbose_name='서비스')),
            ],
            options={
                'verbose_name': '주문 서비스 항목',
                'verbose_name_plural': '주문 서비스 항목',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_photos/%Y/%m/', verbose_name='사진')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='kiosk.serviceorder', verbose_name='주문')),
            ],
            options={
                'verbose_name': '시공 사진',
                'verbose_name_plural': '시공 사진',
                'ordering': ['created_at'],
            },
        ),
    ]
