# Generated by Django 5.2.6 on 2026-01-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_serviceorder_serviceorderitem_serviceorderphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='QuickOil', max_length=100, verbose_name='지점명')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('wifi_name', models.CharField(default='QuickOil_Guest', max_length=50, verbose_name='Wi-Fi 이름')),
                ('wifi_password', models.CharField(blank=True, max_length=50, verbose_name='Wi-Fi 비밀번호')),
                ('estimated_time', models.PositiveIntegerField(default=30, verbose_name='예상 소요시간(분)')),
                ('welcome_message', models.TextField(blank=True, verbose_name='환영 메시지')),
            ],
            options={
                'verbose_name': '지점 설정',
                'verbose_name_plural': '지점 설정',
            },
        ),
    ]
