# Generated by Django 5.2.6 on 2026-01-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_storesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='wifi_name',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='wifi_password',
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='address',
            field=models.CharField(default='경기도 광명시', max_length=200, verbose_name='주소'),
        ),
    ]
