# Generated by Django 5.2.6 on 2026-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_remove_storesettings_wifi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='고객 전화번호'),
        ),
    ]
