# Generated by Django 5.2.6 on 2026-01-10 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_serviceorder_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='전화번호')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='고객명')),
                ('car_number', models.CharField(blank=True, max_length=20, verbose_name='차량번호')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.carbrand', verbose_name='브랜드')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.carmodel', verbose_name='차종')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.fueltype', verbose_name='연료타입')),
            ],
            options={
                'verbose_name': '고객',
                'verbose_name_plural': '고객',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='예약일')),
                ('time', models.TimeField(verbose_name='예약시간')),
                ('customer_name', models.CharField(blank=True, max_length=50, verbose_name='고객명')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='전화번호')),
                ('car_number', models.CharField(blank=True, max_length=20, verbose_name='차량번호')),
                ('expected_oil', models.CharField(blank=True, max_length=20, verbose_name='예상 오일')),
                ('expected_services', models.TextField(blank=True, verbose_name='예상 추가서비스')),
                ('status', models.CharField(choices=[('reserved', '예약'), ('arrived', '도착'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('no_show', '노쇼')], default='reserved', max_length=20, verbose_name='상태')),
                ('source', models.CharField(choices=[('phone', '전화'), ('naver', '네이버'), ('michael', '마이클'), ('walk_in', '워크인'), ('other', '기타')], default='phone', max_length=20, verbose_name='예약경로')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.carbrand', verbose_name='브랜드')),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.carmodel', verbose_name='차종')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.customer', verbose_name='고객')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.serviceorder', verbose_name='시공주문')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약',
                'ordering': ['date', 'time'],
            },
        ),
    ]
