# Generated by Django 5.2.6 on 2026-02-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_alter_reservation_date_alter_serviceorder_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('economy', '이코노미'), ('standard', '스탠다드'), ('premium', '프리미엄'), ('premium_hybrid', '프리미엄 하이브리드'), ('hyperformance', '하이퍼포먼스'), ('racing', '레이싱')], max_length=20, unique=True, verbose_name='티어')),
                ('name', models.CharField(max_length=100, verbose_name='제품명')),
                ('oil_type', models.CharField(max_length=50, verbose_name='오일 타입')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('mileage_interval', models.PositiveIntegerField(verbose_name='교환주기(km)')),
                ('badge', models.CharField(blank=True, max_length=20, verbose_name='뱃지')),
                ('badge_type', models.CharField(blank=True, max_length=20, verbose_name='뱃지 타입')),
                ('is_visible', models.BooleanField(default=True, verbose_name='고객 노출')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '오일 제품',
                'verbose_name_plural': '오일 제품',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='kiosk.carmodel', verbose_name='상위 차종'),
        ),
        migrations.CreateModel(
            name='OilPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_prices', to='kiosk.carmodel', verbose_name='차종')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_prices', to='kiosk.fueltype', verbose_name='연료타입')),
                ('oil_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='kiosk.oilproduct', verbose_name='오일 제품')),
            ],
            options={
                'verbose_name': '오일 가격',
                'verbose_name_plural': '오일 가격',
                'indexes': [models.Index(fields=['car_model', 'fuel_type'], name='kiosk_oilpr_car_mod_edc5e7_idx')],
                'unique_together': {('car_model', 'oil_product', 'fuel_type')},
            },
        ),
    ]
