# Generated by Django 5.2.6 on 2026-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0010_seed_oil_products_and_hybrid_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='ecount_slip_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='이카운트 전표번호'),
        ),
    ]
