# Generated by Django 5.2.6 on 2026-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0011_add_ecount_slip_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='ecount_purchase_slip_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='이카운트 매입전표번호'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='membership_discount',
            field=models.BooleanField(default=False, verbose_name='운산 멤버십 할인'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='ecount_slip_no',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='이카운트 매출전표번호'),
        ),
    ]
